export const eventFormats = [
    'Festival, Fair, Bazaar',
    'Konser',
    'Pertandingan',
    'Exhibition, Expo, Pameran',
    'Konferensi',
    'Workshop',
    'Pertunjukan',
    'Atraksi, Theme Park',
    'Akomodasi',
    'Seminar, Talk Show',
    'Social Gathering',
    'Training, Sertifikasi, Ujian',
    'Pensi, Even Sekolah, Kampus',
    'Trip, Tur',
    'Turnamen, Kompetisi',
    'Lainnya'
]

export const eventTopics = [
    'Anak, Keluarga',
    'Bisnis',
    'Desain, Foto, Video',
    'Film, Sinema',
    'Game, E-Sports',
    'Hobi, Kerajinan Tangan',
    'Investasi, Saham',
    'Karir, Pengembangan Diri',
    'Keagamaan',
    'Kesehatan, Kebugaran',
    'Keuangan, Finansial',
    'Lingkungan Hidup',
    'Makanan Minuman',
    'Marketing',
    'Musik',
    'Olahraga',
    'Otomotif',
    'Sains, Teknologi',
    'Seni, Budaya',
    'Sosial, Hukum, Politik',
    'Standup Comedy',
    'Pendidikan Beasiswa',
    'Tech, Startup',
    'Wisata & Liburan',
    'Lainnya'
]